# 基础镜像
FROM nginx
# author
MAINTAINER muzi

# 挂载目录
VOLUME /home/muzi/projects/muzi-ui
# 创建目录
RUN mkdir -p /home/muzi/projects/muzi-ui
# 指定路径
WORKDIR /home/muzi/projects/muzi-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/muzi/projects/muzi-ui
