# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER muzi

# 挂载目录
VOLUME /home/muzi
# 创建目录
RUN mkdir -p /home/muzi
# 指定路径
WORKDIR /home/muzi
# 复制jar文件到路径
COPY ./jar/muzi-visual-monitor.jar /home/muzi/muzi-visual-monitor.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","muzi-visual-monitor.jar"]